Some cleanup

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,8 +1,17 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
+YELLOW='\033[1;33m'
+RED='\033[1;31m'
+RESET='\033[0m'
 
 VERSION=9.21
 VERSION_SHORT=921
+
+# Console utilities
+function error() {
+	echo -e " !     $*" >&2
+	exit 1
+}
 
 function indent() {
 	c='s/^/       /'
@@ -28,9 +37,18 @@ cd $BUILD_DIR
 mkdir -p $LOCATION/bin
 wget -O gs.tgz $PACKAGE # Couldn't get curl to work for some reason
 tar xvf gs.tgz | indent
-mv $BINARY $LOCATION/bin/gs
 
+# Clean up
+topic "Cleaning up..."
+mv $BINARY $LOCATION/bin/gs | indent
+rm gs.tgz $PACKAGE | indent
+
+# Build runtime environment
 topic "Building runtime environment for Ghostscript to $LOCATION"
-
 mkdir -p $BUILD_DIR/.profile.d
 echo "export PATH=\"\$HOME/vendor/gs/bin:\$PATH\"" > $BUILD_DIR/.profile.d/ghostscript.sh
+
+# Show Ghostscript version
+topic "Getting installed Ghostscript version..."
+GS_VERSION=`gs --version`
+echo -e "${YELLOW}gs v${GS_VERSION}${RESET}" | indent
